name: Build & Deploy to Azure (Linux)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Build React front-end
      - name: Install & build frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      # Install dependencies for back-end
      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      # Deploy the backend folder (which now contains build/)
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: backend
