name: CI / CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - uses: actions/checkout@v3

      # 2. Set up Node.js (needed for building the React app)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies and build the React app
      - name: Install and build React
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      # 4. Deploy the production build to Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: derekwyliecapstone       # ← replace with your actual App Service name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./frontend/build             # ← this is the folder Azure will publish
