name: CI / CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: List entire workspace
        run: |
          echo "=== ROOT DIRECTORY ==="
          ls -R .

      # (We’ll fill in the build/deploy steps once we know where package.json lives)
